#!/usr/bin/env python3

import logging
import os

from config import cfg
from parser import Parser 


def run():
    os.chdir(os.path.dirname(__file__))
    
    cfg.configure()
    if cfg.getboolean('main', 'debug'):
        level = logging.DEBUG
    else:
        level = logging.WARN

    log_fmt = '%(asctime)s [%(process)d] %(levelname)s: %(message)s'

    logging.basicConfig(format=log_fmt, level=level)
    
    parser = Parser()
    parser.update()


if __name__ == '__main__':
    run()
